MaxFightTime: 120 # 单次战斗最大时间 超过时间会进行下一个目标
MaxIdleTime: 10 # 战斗完成后的空闲时间，不能小于5
SelectRoleInterval: 2 # 选择角色的时间间隔 最小为2 避免无法选择角色
FightTactics: # 战斗策略 三个角色的释放技能顺序, 逗号分隔, e,q,r为技能, a为普攻, 数字为间隔时间,a~0.5为普攻按下0.5秒
    - "e,q,r,a~,0.1,a~,0.1,a,0.1,a,0.1,a,0.1"
    - "e,q,r,a~,0.1,a~,0.1,a,0.1,a,0.1,a,0.1"
    - "e,q,r,a~,a~,a~,a~,a~"
TargetBoss: # 目标BOSS 必须保证目标BOSS的位置是有借位信标的，可以少字但是不能有错别字
    - "鸣钟之龟"
    - "燎照之骑"
    - "聚械机偶"
    - "无妄者"